### ISSUE TITLE
Configuration option for name of sender for the server running adminpay / pay commands

### ISSUE THREAD

**Issue by ericgrandt** [ericgrandt/TotalEconomy#116]
At the moment, when the pay and adminpay commands are executed on the server, the sender's name shows up as SERVER/server respectively. A configuration option, in the main configuration file, for what should be displayed in its place would be a nice feature to have. The default value for this option should be set to SERVER so there can be some consistency between the output of both commands.

**Comment by ellapham85** [comment]
Tai sao toi lai khong duoc phi ho tro

**Comment by MarkL4YG** [comment]
@ellapham85 In English please ;)
