### ISSUE TITLE
Create custom jobs from within game

### ISSUE THREAD

**Issue by ericgrandt** [ericgrandt/TotalEconomy#133]
The idea is to run a command that will allow someone with the correct permissions to set a name, salary, and the blocks/items/mobs reward amounts (exp/money) for a custom job, all within game.

**Comment by MarkL4YG** [comment]
If possible some GUI would be very nice for this! 👍 
I'm thinking of something like the way shops work on pvp servers just that one could put mob heads in for getting paid/exp for killing the type of mob. Or a block for mining this block type.
Something like this would make custom configurations way easier imo.

**Comment by Erigitic** [comment]
I like this idea. It will obviously take a while to add, but I think the outcome would look amazing! Great suggestion!

**Comment by codydbgt** [comment]
perhaps u could put items in a chest and then put a sign on the chest the first line being the jobsetname and the 2nd and 3rd line being the xp and $ then u click with glowstone and ur done other plugins use redstone and gunpowder so far i don't think any use glowstone

**Comment by MarkL4YG** [comment]
In my opinion, that is rather complicated to use. Especially as job sets also have different actions (``break``, ``place``, ...) which we would have to detect. And even more, when we're talking about traits and keys which are used to further specify block and item type but are not necessarily transferable from our point of view.  
  
I think that a set of commands to create/delete/edit job sets is more straight forward. One could add blocks to a ``break`` action by clicking/looking at the respective blocks e.g. while adding items to the ``craft``/```fish``/... actions by holding the item in hand.

**Comment by Erigitic** [comment]
I like the idea @codydbgt , though it would be exceptionally difficult to implement since, as @MarkL4YG pointed out, job sets have a bunch of different actions. It might be a challenge to distinguish between the different actions if using a chest.

**Comment by codydbgt** [comment]
the chest would have a sing ? ... copy it from carrot shop its open source just add the signs to have extra info for the triggers on one of the lines

**Comment by MarkL4YG** [comment]
The issue with that method is many mods and even some vanilla items/blocks do not solely rely on the ID to identify the item/block. Having items in the chest will allow us to determine the item type but not directly how to identify that item when crafted e.g. .  
Not even mentioning when the item is for a block and we need the block type instead of the item type but have no idea of the blocks traits.  
It is way less complicated to use a method that allows us to directly get an instance of the target type directly. (Looking at a particular block, having a particular item in hand, etc.)  
This way, specifying the jobset and action to add the target too could be enough to update the set accordingly.

**Comment by codydbgt** [comment]
im a dev my self can u throw some api ?? i don't see how u cant do this . aside from all that i really just want to be able to add a chest full of blocks ...

**Comment by MarkL4YG** [comment]
Blocks are identified by ``BlockType#getId()``.  
But in addition, many blocks are actually divided into different variants using ``Trait``s which can be freely named and can hold any primitive value the programmer likes.  
Same thing with ``ItemType#getId()`` and ``Key``s goes for items.  
  
Therefore, we need to translate from an item with (a) key into a block with (a) trait when creating a block-based action from an inventory.  
If ``ItemType#getBlock().get() => BlockType`` respects this translation and actually gives us a the block type with the correct trait set, that is less of a problem. (Haven't tested this yet.)  
But, in addition, we will need to guess what trait to base the identification on which can be difficult if there are multiple traits on a block. (``FACING`` normally is a trait too, btw)  
  
And even when generating item-based actions from inventories, we need to know what ``Key`` to base the identification on as they can have multiple too.
