### ISSUE TITLE
New version tracker

### ISSUE THREAD

**Issue by ericgrandt** [ericgrandt/TotalEconomy#134]
Automatically check for new versions of Total Economy on server start. This can easily be done using the OreAPI: https://docs.spongepowered.org/stable/en/ore/api.html.

**Comment by MarkL4YG** [comment]
Just leaving [this](https://github.com/MarkL4YG/Homework_Server_Installer/blob/bleeding/src/main/java/de/mlessmann/updates/indices/nativeGHReleases.java) here in case it's of interest to you.

**Comment by Erigitic** [comment]
@MarkL4YG This will definitely be helpful. Thanks.

**Comment by MarkL4YG** [comment]
You're welcome :)
Just to explain a little: The project contains a whole section dedicated to update detection that's supposed to be able to support indices with different syntax whenever a class dedicated to the syntax is available.
For sponge plugins based on GitHub it's a bit overpowered but the code dedicated to GitHub might be useful anyways.

**Comment by Erigitic** [comment]
For this we have to use the OreAPI: https://docs.spongepowered.org/stable/en/ore/api.html. Seems simple enough.
