### ISSUE TITLE
Custom level up formula

### ISSUE THREAD

**Issue by ericgrandt** [ericgrandt/TotalEconomy#152]
Add the ability to set the formula for when to award a level up from the configuration file. 

Currently the formula is simply: curLvl * 100

**Comment by MarkL4YG** [comment]
@Erigitic Depends on what we/you 'd like the JBRs to support I guess. I can think of some permanent issue to collect ideas and have a list about what's supported.

**Comment by MarkL4YG** [comment]
I've created an issue to track the progress.  
Since this may result in an overhaul of the class I'll continue my suggestions in the tracking issue.
