### ISSUE TITLE
[Track] Expand JBR conditions

### ISSUE THREAD

**Issue by MarkL4YG** [ericgrandt/TotalEconomy#153]
Permanent issue to track functionality and suggestions of the ``JobBasedRequirement`` class for configurable conditions.

General JBR implementation
---
- [X] Job set command
  - [X] Single (Commit: 446f46dcf0558b5d4d128262423c46a0aa057ba6 Target: ``1.6.0``)
  - [ ] Multiple
- [ ] Salaries (Proposed by #152)

Specific JBR features
---
- [X] Permission
  - [X] Single (Commit: 446f46dcf0558b5d4d128262423c46a0aa057ba6 Target: ``1.6.0``)
  - [ ] Multiple
- [X] Level at specific job
  - [X] Single (Commit: 446f46dcf0558b5d4d128262423c46a0aa057ba6 Target: ``1.6.0``)
  - [ ] Multiple

**Comment by MarkL4YG** [comment]
A first thought of mine for this is to rename the class to ``TEConfCondition`` and creating a subclass ``TEConfConditionValue`` which also stores the value (generic) that should be used when the condition is met.  

I would expand the ``TEConfCondition`` with an ``evaluate(Player player)`` method which returns a boolean to indicate whether the player fulfills the conditions or not.
I also suggest a serializer to create ``ConfigurationNodes`` from instances, instances from nodes and an output that a player can read.  

An example for the last could be a method ``TEConfCondition.toText(@Nullable Player player)`` which also colors the output based on what conditions are met.

As for the salaries: I suggest allowing the administrator to set the salary value to a set of conditions (maybe a list of ``ConfigurationNode``s) and when the salary should be determined the condition with the highest salary which the player still fulfills should return the value.


I suggest a similar implementation to any future and existing usages of the requirements and want to mention that I also think of keeping requirements optional so the administrators can always (e.g.) just write "salary=30" instead of the supposedly complex condition stuff while not breaking anything. 
---
This is a pretty big change to salaries and the configurations complexity so this should be carefully developed in a second branch as it will break configurations and may produce a lot of bugs.

**Comment by MarkL4YG** [comment]
An implementation of optional conditions could be by telling the ``TEValueCondition`` to deserialize itself form a node and just be always fulfilled when the node was just a value.
A simple check for whether the node contains nodes or not could do this.

**Comment by MarkL4YG** [comment]
@Erigitic I've created an example implementation in [my fork](https://github.com/MarkL4YG/TotalEconomy/tree/feature/conditions).
It allows jobs to be defined like this for having a single condition:
```hocon
    test {
        condition {
            j=miner
            l=2
        }
    }
```
or like this for having multiple conditions:
```hocon
test2 {
        condition = [
            {
                job=miner //Shorthand is "j"
                level=2 //Shorthand is "l"
            }
            {
                j=warrior
                l=2
            }
        ]
    }
```
The last commit also includes a [TECondition#toText](https://github.com/MarkL4YG/TotalEconomy/blob/feature/conditions/src/main/java/com/erigitic/jobs/conditions/TECondition.java#L194) method that allows the ``JobInfoCommand`` to correctly list the conditions as seen [from here](https://github.com/MarkL4YG/TotalEconomy/blob/feature/conditions/src/main/java/com/erigitic/commands/JobInfoCommand.java#L107)

---
I think a similar implementation could interpret the salary node like this:
```hocon
    salary = [
        {
            j=test2
            l=10
            value=20 //Shorthand is "v"
        }
        {
            j=test2
            l=20
            v=40
        }
    ]
```
in addition to the normal interger value.

**Comment by Erigitic** [comment]
I think this will work. This is not high priority right now but should be something that we get added.
