### ISSUE TITLE
EXP bar for current job

### ISSUE THREAD

**Issue by ericgrandt** [ericgrandt/TotalEconomy#177]
If possible, an exp bar that looks like the the ender dragon's health bar can be used to display progress in the player's current job.

**Comment by MarkL4YG** [comment]
Sounds interesting, I'd suggest three modes:
1. Hidden
2. Fade out (just display a few seconds after exp gain)
3. Always shown

**Comment by Erigitic** [comment]
Agreed. We could adjust the `/job toggle` command to take in a third argument in order to specify what is being toggled (notifications or exp bar). This way we can avoid creating a completely separate command.

**Comment by MarkL4YG** [comment]
Yup and remember to use ``GenericArguments.choices`` so Sponge handles autocompletion for us.

**Comment by Erigitic** [comment]
I think this should wait till this PR is merged: https://github.com/SpongePowered/SpongeAPI/pull/1534. Currently, as far a I can tell, the only way to see what boss bar a player is attached to would be to store them all in a list. I feel like this could become an issue if we had to loop through that list every single time we needed to update the boss bar.

**Comment by MarkL4YG** [comment]
Agreed
