### ISSUE TITLE
Payments based on permission

### ISSUE THREAD

**Issue by ResqDiver1317** [ericgrandt/TotalEconomy#189]
I like that TE includes the Jobs functions, and we are looking at implementing that into a server we are working on building, but for our current server, we replaced Economy Lite with TE as EL just flat out was not working (everything we tried would give us an internal error). 

On this server, we want 2 pay scales, 1 for regular member, and one for our premium members and staff. 
Is it possible, rather than having players place themselves in a "job" for premium, can we just give the permission node totaleconomy.job.member and totaleconomy.job.premium to the proper ranks and create jobs in the jobs file with: 

member {
        require {
            level=0
            permission="totaleconomy.job.member
        salary=300
    }

premium {
        require {
            level=0
            permission="totaleconomy.job.premium"
        }
        salary=600
    }

With this method, would they have to assign themselves to the jobs, or can it be automatic based on the permission node they have through their rank in LuckPerms?

**Comment by Erigitic** [comment]
The way it currently works, the player, or an admin with proper privileges, would have to set the job themselves. We can look into this to see if we can get this change added. Thanks.

**Comment by ResqDiver1317** [comment]
Thanks for the quick response! I guess part of me has been spoiled by how we handled this on our bukkit/spigot based servers. On those, we use a plugin called TimeIsMoney which simply pays out an amount based on what permission node the player has. I've been having to workout different ways of doing a lot of stuff now that I'm dealing with a Sponge based server and for the most part, all of you plugin/mod developers have done a great job providing tools for us to do what we need, even if we do have to go about it different ways. I'm really looking forward to launching our new server in about a month that a big focus of the server is going to be a town/city build and will be heavily driven around the Jobs system that TE has. I think it will be a fun new experience for our community when it launches :)

For our existing servers where we are kinda stuck in our old ways, I'm really hoping the permission based payments is something you can get added! Keep up the great work!!

**Comment by MarkL4YG** [comment]
I would say a player option rather than a permission would be a better idea for storing premium payments as options can contain values and can be set by groups which makes a simple plugin just paying out that value incredibly small (basically the recurring task).
In that case you'd just add premium players to a group instead.

**Comment by MarkL4YG** [comment]
In that case TE (in my view) wouldn't be responsible for such a feature.  

Although detecting jobs based on permissions would be a brute-force-ish way to allow multiple jobs per player.

**Comment by Erigitic** [comment]
@MarkL4YG This was added by you correct? The job permissions.
