### ISSUE TITLE
[SQL] Jobs to strict

### ISSUE THREAD

**Issue by MarkL4YG** [ericgrandt/TotalEconomy#196]
As jobs are still defined in a file while the information about player progress is stored in a database renaming jobs will mess things up. Possible solutions for this would be:
* Implementing a detection that alters the table columns
* Restructuring the concept

I'd choose the second one and would assign jobs a single ID (maybe UUID) which is generated when the job is loaded.
We then can use the name just as a decorative thing to display to players which removes the mess when a job is renamed.  
If we remove the levels and exp tables we could create a new one called ``job_progress`` for example. Which has the rows ``job_id, player-UUID, exp, level``. This way the columns always stay the same all the time which makes altering the table unnecessary.  This'll create a row for each player and job though so to minimize the rows I'd only create the row when the player first takes the job OR even when he collected exp the first time.

**Comment by MarkL4YG** [comment]
Note: Using Job-IDs and displaynames one could even localize job names ;)

**Comment by Erigitic** [comment]
I like the idea of using a UUID for a job with the name of it just there for display. Makes a lot more sense. And same thing with the renaming and consolidation of the exp/level tables into a single `job_progress` table. I'll go ahead and work on this one.

**Comment by Erigitic** [comment]
Does #243 take care of this issue? If so is it ok if I close it?

**Comment by MarkL4YG** [comment]
Yes indeed. As I had to touch the whole db schema and write migrations anyways I decided to go ahead and include the change to ``UUID``s.  
Personally I would only close the issue once the PR is merged or superseded otherwise.

**Comment by YumaYamamoto** [comment]
Can you help me with that? I use a mysql databank since today and the jobs dont work now anymore...

**Comment by MarkL4YG** [comment]
@YumaYamamoto Your problem is not related to the this issue. If you need help either open an issue or ask in the Gitter chat.
