### ISSUE TITLE
Issue with Sponges implicit wildcard.

### ISSUE THREAD

**Issue by MarkL4YG** [ericgrandt/TotalEconomy#205]
Aside from wildcard permissions known from Bukkit ( ``someplugin.someperm.*`` ) Sponge has implicit wilcards where ``someplugin.someperm`` would actually also mean ``someplugin.someperm.*``.  
  
This is an issue since the JobCommand requires users to have ``totaleconomy.command.job`` implicitly granting permissions to ALL job sub commands.  
  
Some permission plugins already avoid implementing this behavior due to this while some (like LuckyPerms e.g.) provide configurable options and some don't.  
Nontheless permissions should change so this is prevented from happening.

**Comment by amekusa** [comment]
Agreed. It should be:
- `/job`       requires **only** `totaleconomy.command.job.info`
- `/job set` requires **only** `totaleconomy.command.job.set`
