### ISSUE TITLE
Add optional parameter to prevent negative balances with admin pay

### ISSUE THREAD

**Issue by ericgrandt** [ericgrandt/TotalEconomy#215]
I'm thinking something along the lines of:

/adminpay Erigitic -250 [true/false]

This will be an optional parameter that'll default to false, thus allowing balances to go negative when using admin pay. This is the current behavior. If true, balances will be prevented from going below 0.

**Comment by MarkL4YG** [comment]
Remember to raise a ``CommandException`` so command blocks know the payment failed
