### ISSUE TITLE
Handle undefined message keys when retrieving from messages file

### ISSUE THREAD

**Issue by ericgrandt** [ericgrandt/TotalEconomy#221]
With new messages being added to the message_en.conf file, a way to handle these messages not existing in other locales must be added to avoid any errors. I'm not entirely sure on the best way to go about doing this, but a temporary solution could be putting in the English translation into each file and just waiting for it to be translated.

Or if a lightweight translation library exists, that doesn't involve users having to download something else alongside Total Economy, that could be used as well.

**Comment by MarkL4YG** [comment]
I'd suggest copying the language file from the english asset file when it doesn't exist.
