### ISSUE TITLE
Add salary in items

### ISSUE THREAD

**Issue by Krosta8** [ericgrandt/TotalEconomy#222]
Hello,
Would it be possible to set salary in items?
For example "minecraft:stone=5;minecraft:wood=3"

I just want to have a method, how to give players some items in intervals, when they are playing on the server.

Thank you,
Krosta8

**Comment by MarkL4YG** [comment]
Interesting idea... I guess I'll have a look at that at some point.

**Comment by Erigitic** [comment]
I can definitely see this being a possibility. This would give us another good reason to clean up the code we currently have for salaries and jobs as a whole.
