### ISSUE TITLE
Multiple jobs/leveling/titles not supported?

### ISSUE THREAD

**Issue by smmmadden** [ericgrandt/TotalEconomy#230]
Minecraft: 1.12.2
SpongeAPI Version: 7.0.0-SNAPSHOT-0ede943
Sponge Forge Version: 1.12.2-2529-7.0.0-BETA-2755
Forge: 14.23.1.2555
Total Economy Version: 1.7.1 and 1.7.1-API_7
JVM: 1.8.0_152
Server: Windows 10 Pro
Permissions: LuckPerms Sponge 4.0.62

Is it possible to have players working in more than one job at a time?  Playing minecraft is about skills in multiple areas of the game and all are done together as a whole.  For example, I can farm, hunt, mine and build so each would help the player to earn monies and advance.  Having multiple jobs also allows players to see where they earn the most money (farming, hunting, fishing, etc.).  Currently, it seems that you get one job and have to use /job set xxx to switch jobs before you can begin earning in it and then your balance from farming say gets carried forward to the next but you didn't earn that money in that job so it can be deceiving. I'd love to see this area expanded more like ZRips plugin for [Jobs Reborn](https://www.spigotmc.org/resources/jobs-reborn.4216/) that I use on my other servers.  In it, I can define multiple jobs, set players maximum # of jobs they can have, earn multiple titles as the player levels up in a job and get statistics to name a few on what I earned in each and what level I am for each job. 

I suppose I could create a custom job and mix a bunch of stuff into that category, but that's not quite the same unfortunately.  Thanks -Steve

**Comment by smmmadden** [comment]
Looks like I was partly wrong above.  It does appear to properly split out the job, experience and levels but does not keep the balances for each split.
![image](https://user-images.githubusercontent.com/10309346/34419530-68009f14-ebd2-11e7-8450-077375fc0534.png)
So I'd recommend using the dollar-balance as a combined total of all monies earned and then having a earnings or balancing field under each job.  So when someone uses /balance, /balancetop or /viewbalance they split out each job with the experience, job level and amount earned.

Example:
![image](https://user-images.githubusercontent.com/10309346/34419806-fd2f8734-ebd3-11e7-9321-8b6fafc03c52.png)

**Comment by Erigitic** [comment]
I do think that it would be beneficial to allow multiple jobs to be leveled up without having to do `/job set [somejob]` over and over again. I plan on reworking the entire job system someday so it is more streamlined and fleshed out.

**Comment by smmmadden** [comment]
could you add to it, the additional actions shown below that are all available in later versions of MC?
break - Breaking blocks
place - Placing blocks
kill - Killing mobs
catch - Catching fish
**breed** - Breeding for friendly mobs
**shear** - each of the sheep colors
**tame** - taming of friendly mobs
**craft** - crafting tools (swords, axes, helmets, armor, etc)
**repair** - repairing of crafted items
**smelt** - smelting of ores
**eat** - eating of specific cooked foods (cooked_rabbit, baked_potato, etc)
**milk** - milking of cows and mushroomcows
**dye* - dyeing of leather armor
**enchant** - enchanting of items like swords, axes and armor
**brew** - brewing of redstone, glowstone_dust, spider_eyes, etc

Thanks!  - I'm happy to do testing on this if/when you have something available.  I've done the same for the other developer with a couple of his plugins. -Steve

**Comment by Erigitic** [comment]
I'll keep these all in mind. Thanks.

**Comment by pigneedle** [comment]
I think the most important feature would be to add crafting. It would even make sense to add crafting detection, release, then add the other features later. It would also help me with the server I am setting up.

**Comment by MarkL4YG** [comment]
In what order those features are released depends mostly on complexity. But I consider all those to be accepted requests anyways.

**Comment by pigneedle** [comment]
They all make sense, of course. I'm just saying you already have mining. Crafting seems like the next logical job to prioritize as it is a vital part of Minecraft. (It's even in the name!)

**Comment by Baylorai** [comment]
Has this been picked back up at all? using the plugin totaleconomy and would love to see it have ability to join multiple jobs at once

**Comment by Erigitic** [comment]
It has not been picked up. Total Economy is currently being rewritten for API 8, so I'll be sure to keep this mind while rewriting the job related code.
