### ISSUE TITLE
Increase experience as job level increases

### ISSUE THREAD

**Issue by ericgrandt** [ericgrandt/TotalEconomy#237]
Eventually it will get to the point where it takes an incredibly long time to level up. A modifier should be added onto the experience reward in order to increase the speed of progression at later levels.

**Comment by smmmadden** [comment]
If it helps, I'd check with Zrips (owner of Jobs Reborn - Spigot) but the leveling he's using for his plugin which supports one-to-many jobs, one-to-many levels and in the config file, it's incremented like this.
income-progression-equation: baseincome+(baseincome*(joblevel-1)*0.01)-((baseincome+(joblevel-1)*0.01) * ((numjobs-1)*0.05))

points-progression-equation: basepoints+(basepoints*(joblevel-1)*0.01)-((basepoints+(joblevel-1)*0.01) * ((numjobs-1)*0.05))

experience-progression-equation: baseexperience-(baseexperience*((numjobs-1) *0.01))

This model supports assigning one-to-many titles to each job & level.  For example in my titleConfig.yml file I assign job titles based on level increments.  So as a player reaches a certain level they are notified of a title change for that job.  Continue doing well, you continue to get higher titles (no restrictions).
Titles:
  Rookie:
    Name: Rookie
    ShortName: BR
    ChatColour: WHITE
    levelReq: 0
    JobName: Builder
  Laborer:
    Name: Laborer
    ShortName: BL
    ChatColour: WHITE
    levelReq: 10
    JobName: Builder
  Engineer:
    Name: Engineer
    ShortName: BE
    ChatColour: WHITE
    levelReq: 30
    JobName: Builder
  CivilEngineer:
    Name: CivilEngineer
    ShortName: BCE
    ChatColour: WHITE
    levelReq: 60
    JobName: Builder
  ConstructionForeman:
    Name: ConstructionForeman
    ShortName: BCF
    ChatColour: WHITE
    levelReq: 95
    JobName: Builder
  BossBuilder:
    Name: BossBuilder
    ShortName: BBB
    ChatColour: WHITE
    levelReq: 150
    JobName: Builder
  MasterBuilder:
    Name: MasterBuilder
    ShortName: BMB
    ChatColour: WHITE
    levelReq: 200
    JobName: Builder

For my worlds, I allow up to 4 jobs (out of 14 defined) to be earning money on.  I asked Zrips if he could make a sponge/forge version but that's out of his area of experience.  So it may be worth using it as a model or convert it to a mod?  Hope this helps.
