### ISSUE TITLE
[SQL] Refactor database concept

### ISSUE THREAD

**Issue by MarkL4YG** [ericgrandt/TotalEconomy#243]
As already discussed in #196 #195 and on Gitter the database concept is currently inefficient for  maintenance as it's to static due to having jobs and balances in columns for example which would require administrators to alter the tables whenever they add (or remove) a job or a balance.

I propose a refactor which will also follow in form of a PR.
(Code's located in [my fork](https://github.com/MarkL4YG/TotalEconomy/tree/proposal/sql-refactor))

Additional details will follow in the PR but at the moment the basic goals are:
* Re-design database tables so they're less static
* Re-design account classes so they fit better to the separate tasks of being linked to a database or a ConfigurationNode (_abstract: their storage system_)
* Re-design ``VirtualAccount`` concept to allow them to be handled as player accounts whenever possible (minimizes code duplication and possible issue causes)
* Change jobs to use ``UUID``s too so they can be uniquely identified and change names without resetting progress
* Automatic migration from the current schema and configuration (including automatic migration for future updates)
---
Status: So far the basics seem to work. I'm currently doing tests whenever I have spare time at hand.

**Comment by Erigitic** [comment]
Is the automatic migration something temporary that can easily be removed in a later release, after everyone has already migrated?

**Comment by MarkL4YG** [comment]
The automatic conversion consists of about three parts depending on where you define the borders.
### Job migration
Converts the old flat file storage to use ``UUID``s instead of names.
Is one code block in the JobManager.
-> Could be removed but may be reusable for adding new jobs from the config so could just stay in place.
### Release migration
Migration code that prepares the current flat file format for migration through the next method.
-> May be removed along the next releases. But may also stay in place to allow conversion from the current structure to any future structure.
### SQL migration
The most sophisticated migration code of the three. This includes schema version tracking and migration using ``Migrator``s. I would not recommend removing any of this during future releases.

---
This will be more clear once I wrote the documentation for the migration as I aim to provide you with example wiki pages.
