### ISSUE TITLE
Add Support for custom Actions (1.12.2+)

### ISSUE THREAD

**Issue by smmmadden** [ericgrandt/TotalEconomy#244]
Minecraft: 1.12.2
SpongeAPI: 7.1.0-SNAPSHOT-dfc5c4a
SpongeForge: 1.12.2-2555-7.1.0-BETA-2842
Minecraft Forge: 14.23.1.2599
Total Economy Version:  1.7.1-API_7

### Description of issue
Hi - I’m looking to expand the Jobs and Job Sets in Total Economy but not sure what syntax is appropriate.  Should I be using the FQN of the block or entity in the actions sections?  I see both uses of them on your help pages.
mobs {
kill {
**creeper** {
exp="10"
money=“1.00”
}
break {
“**minecraft:log**” {
exp="10"
money=“0.50”
}
“**minecraft:coal_ore**” {
exp="25"
money=“2.00”
}
}
What do you do for the data id that goes with some of the items? 
Is there a right-way, preferred way or new way we should be expanding them out so they don’t break in 1.13? 
Thanks -Steve

**Comment by smmmadden** [comment]
One other question with the formatting of the sets.  If I wanted to add additional to a job, is it comma separated, new line or can it not contain more than one?
        sets=[
            lumberjackSet
        ]
Couldn't this just become 
sets=[lumberjackSet,ores,foobar] 

on one line for simpler editing/reading?

**Comment by smmmadden** [comment]
I would like to also integrate this mod with my Pokecube Revival Server and use the "catch" action for catching the pokemobs in a cube.  There is also an option for battle, which would be nice if the player wins the battle, they get xx points and xx money.  However, if they lose a battle, they lose xx points and/or xx money.  I'm thinking this would be a catch and battle action.  What do you think, is this doable?

**Comment by MarkL4YG** [comment]
1. Fully qualified ID is correct if I remember this correctly.
2. No you can't inline the three values. Afaik hocon doesn't allow this.
3. In order for that to work the mod would need to fire a Sponge event which TE would need to listen to. I'd say that's more something for a custom plugin.

**Comment by smmmadden** [comment]
Thank you MarkL4YG - that's what I thought, but wanted to make sure.  It would make it easier to read, but it is what it is. :-)

Do you know if there is support for criteria triggers? https://github.com/Thutmose/Pokecube/issues/259

**Comment by smmmadden** [comment]
are there plans to add to the list of actionable sets?  In MC, other actions are crafting, enchanting, dyeing, repairing, smelting, brewing, Taming, Breeding, shearing and milking.  Adding these would heighten the experiences of users.

**Comment by MarkL4YG** [comment]
I expect the vanilla triggers all to be included at some point but I would guess that the triggers for catching a pokemob aswell as winning or loosing a fight are too specific in order to be implemented by default.  
As far as I can see right now criteria triggers are a [Forge feature](http://jabelarminecraft.blogspot.de/p/minecraft-modding-custom-triggers-aka.html) which means this would be SF-only code. It appears SpongeAPI 7 may have support for that but I only took a quick'n dirty Google search.     
While this doesn't mean it's never going to be supported it is likely that this takes priority after generic features that can be useful in both versions. Say chest shops, metadata (id traits) and similar stuff.  
However you can always feel free to engage into TE yourself using proposals, assisting with knowledge (maybe about criteria triggers in this case) or similar stuff.  
If you want to do so I suggest you join the Gitter chat.

**Comment by MarkL4YG** [comment]
@smmmadden @Erigitic I suggest renaming this issue to something along this line: "[Forge] [Jobs] Add support for custom actions".  
I suspect more of this to be incoming in the future for other forge mods so I figure that support for this should be added at some point,

**Comment by Thutmose** [comment]
If you do add an API that can be used to add in custom jobs or actions, then I would probably be willing to write a compatibility module for pokecube to support this, I already have a framework for making compatibility modules for random mods, so it wouldn't be too much of an issue for me to do, having an API to work off will help greatly however.

**Comment by MarkL4YG** [comment]
I would guess that there may be a way of achieving this without the need of an additional API.
I will take a look into this at some point but for now I'm focusing on the SQL refactor.  
If you however wouldn't mind taking a look that would be greatly appreciated. Feel free to report your findings.

**Comment by MarkL4YG** [comment]
With the action refactor, custom registered actions become more likely to be supported as we approach a more robust and generic version of the action handling code.  
I will come back to this, once the action refactor has been merged and craft actions are implemented.
