### ISSUE TITLE
Make some functions static if appropriate

### ISSUE THREAD

**Issue by ericgrandt** [ericgrandt/TotalEconomy#247]
After looking through the code, I've come to the realization that a lot of functions could be made static as they do not depend on any members from the class they are initialized in. The goal here is to reduce the amount of objects we have to pass to the constructor of other classes, in turn making the code easier to understand and manage.

**Comment by MarkL4YG** [comment]
It's not like you asked me to remove statics before ¯\\\_(ツ)\_/¯.  
👍 for this one.  
Maybe Sponge will also mature in such things with the planned economy API refactor.

**Comment by Erigitic** [comment]
Yeah, I realized my mistake while looking over the code earlier today. Sorry about that.

**Comment by MarkL4YG** [comment]
No worries. :wink:
