### ISSUE TITLE
Shift click shop items to purchase a stack

### ISSUE THREAD

**Issue by ericgrandt** [ericgrandt/TotalEconomy#253]
A user who is not the shop owner should be able to shift click shop items in order to purchase more than one at a time. If the shop owner shift clicks the item, this should still behave as it does now where it removes all the items in that slot.

**Comment by MarkL4YG** [comment]
My suggestion is a modifier in the way SpaceEngineers uses.
With ``shift`` being full stack, ``ctrl`` fraction (maybe 16?) and single click obviously one at a time.

**Comment by smmmadden** [comment]
I agree, it would at least make it more consistent if not already.  I'll be testing each option later today and will provide results.
