### ISSUE TITLE
Backport of TE1.8 to API5/MC1.10.2?

### ISSUE THREAD

**Issue by ResqDiver1317** [ericgrandt/TotalEconomy#254]
I am really interested in the new updates for Total Economy and will be using it on a new custom server I'm putting together for our community. I would like to know though if there is any possibility to have this new version/features made available for those of us that are still running 1.10.2 modpacks with Sponge API5 as it is still a pretty strong platform base for modpacks. I know everything is moving to 1.12.2/API7, hence why the new server I'm setting up will be on that, but there is still TONS of servers running 1.10.2/API5.

If not, I completely understand, but if there is anyway possible, that would be awesome!

**Comment by MarkL4YG** [comment]
I wouldn't mind to take a look for what needs to be adapted as I already need to do that for API-6 to 7 for the SQL proposal.

I'll get back with info when I took that look.
Of course if Eric isn't faster than me ;)

**Comment by Erigitic** [comment]
I'll leave this one to you @MarkL4YG. Thanks.

**Comment by MarkL4YG** [comment]
As far as I know a build against API-6 should also do the job for API-5 so I started the backport for API-6.  As of now I've yet to find out how much of an effort this may end up being but so far the biggest challenge is IntelliJ 2018.1 failing to load the SpongeVanilla project correctly ...

**Comment by MarkL4YG** [comment]
@ResqDiver1317 I will release a test-jar on my fork before submitting the PR to Eric. You may want to test it in a testing environment to see if the port was successful. 
Here is [the link to the release](https://github.com/MarkL4YG/TotalEconomy/releases/tag/1.11.2-1.8.0-dev).

**Comment by MarkL4YG** [comment]
This will be revisited after the rework of the sql-refactor.  It just makes more sense to do the port afterwards so it'll keep the legacy and the stable version on the same database format.

**Comment by Erigitic** [comment]
I kind of feel a legacy version for API 5 isn't worthwhile anymore. Last stable API 5 release was over a year ago. And I think at this point, considering some of the features of Total Economy, it would be a very large amount of work to get things working 100%. @MarkL4YG Thoughts? Legacy versions should still be made for more recent versions of Sponge though.

**Comment by MarkL4YG** [comment]
For the moment I'll focus on the sql-refactor and bug hunting regarding TotalEconomy.  
I am however still interesten in taking a look into how much efford would be needed to backport to API 6.  
If the efford required is not that high, we can consider backporting to API 6 as that version is likely to be compatible to API 5. Many plugins for API 6 can be run in API 5 just fine but we'lll see.
