### ISSUE TITLE
Indicate that a chest is a chest shop

### ISSUE THREAD

**Issue by ericgrandt** [ericgrandt/TotalEconomy#265]
Chest shops just look like normal chests. Somehow we should indicate that a chest is actually a chest shop. Maybe place a sign on it, or display text above it.

**Comment by Erigitic** [comment]
I do agree that the holographic display would be cool, but you do bring up a good point about it being an issue when there are multiple shops near one another. I'm sure the sign will do just as well of a job without causing a mess of text on the screen.

**Comment by MarkL4YG** [comment]
@DiamondArrow Remember that TE shops can hold multiple items so this can indeed get a little crowded.

If it's not to much work maybe an approach of letting the shop owner decide is also an option.

**Comment by DiamondArrow** [comment]
@MarkL4YG I’m not too sure what you mean it’ll get crowded.
To clarify, I suggested the same concept but the hologram will show <player>’s shop and the item entity will be the player’s head.

**Comment by MarkL4YG** [comment]
So you wouldn't show the items actually sold at the shop? In that case that would work.  
Although it also seems a little redundant in mall-like shops with several chests next to each other don't you think?

**Comment by DiamondArrow** [comment]
@MarkL4YG my thinking behind it is because the holograms only show up when looked at. Therefore the floating player heads will indicate the chest is a shop without having to directly look at each chest to see if a hologram pops up

**Comment by MarkL4YG** [comment]
@DiamondArrow I think that would still cause a lot of floating player heads in malls.
I think only displaying the display when looked at is the best solution here.
