### ISSUE TITLE
Feature Request: Chestshops sortable (by shop owners)

### ISSUE THREAD

**Issue by Joker4632** [ericgrandt/TotalEconomy#268]
Feature Request: Chestshops sortable (by shop owners)

**Comment by Erigitic** [comment]
When you have time would you mind fleshing this out a bit? What would you like sorting to entail and is there a preferred way to go about sorting (command, hotkey, etc.)?

**Comment by Joker4632** [comment]
In the current Version, you could just add items to the shop without any influence where it will be placed in the shop. Ok it will be placed in the first empty slot, but when i refill the shop or like adding more of an item which is not at the last position, stack of the same item will be all over the shop without any sorting.
So it would be nice if the shop owner could replace the items in his shop or at least adding ah shortcut or button to autosort the chestshop

**Comment by MarkL4YG** [comment]
maybe a keystroke to move items left/right is possible.

**Comment by Joker4632** [comment]
yeah that would be an idea
