### ISSUE TITLE
[Feature Request] Migrator from ecolite?

### ISSUE THREAD

**Issue by KhaozFrost** [ericgrandt/TotalEconomy#281]
I'd like to switch from Ecolite to totaleco due to the multi currency support that ecolite says it offers but doesnt implement it correctly but i dont see a way to do that without losing my entire database of balances; so was wondering if totaleco has a migration option the same way ecolite did.

**Comment by MarkL4YG** [comment]
Well, migrating from one DB schema to another shouldn't be that much of an issue if you know a thing or two about SQL.
I've started a project called ``TESqlHelper`` in which such a feature may make sense but neither did I ever use EcoLite nor do I have knowledge of their database schema.
Maybe I can think of something if you help me with a little more information.

**Comment by KhaozFrost** [comment]
[data.zip](https://github.com/Erigitic/TotalEconomy/files/2139236/data.zip)
not very intellectual on the subject but i can provide the database itself if that helps.

**Comment by MarkL4YG** [comment]
I'm going to take a look and get back to you

**Comment by KhaozFrost** [comment]
it doesnt have jobs or shops. its just economy

**Comment by MarkL4YG** [comment]
The ore page did link a plugin called "JobsLite" if I remember correctly.
