### ISSUE TITLE
[Request] More Shop Options

### ISSUE THREAD

**Issue by tridaak** [ericgrandt/TotalEconomy#284]
The plugin allows for multi currency, but seems you cannot set different currencies for shop items. Was wondering if this could get added in.

Was also wondering if we could set names to the shops, currently it's set as [User]'s Shop, but would be neat if we could change that, so organizing could be easier. Also if something like https://ore.spongepowered.org/RandomByte/Holograms could be added on top of the shops with the shop name, would help users navigate player shops.

Lastly, didn't see permissions to override permissions for shops (for admins to remove shops). 
Would also be neat to see meta values for number of shops owned, sales tax I:, and cost of opening a shop.

**Comment by MarkL4YG** [comment]
>  you cannot set different currencies for shop items  

Yes. Right now that's the case but I would assume that supporting non-default currencies shouldn't be that hard.  

> something like [...] could be added on top

There is already something like that planned. The discussion is here: #265  

> didn't see permissions to override permissions for shops  

The permissions are ``totaleconomy.command.shop.stock`` and
``totaleconomy.command.shop.buy`` but I agree that a few more would indeed make sense.  
Maybe @Erigitic can find some time for that 😄

**Comment by Erigitic** [comment]
I plan on expanding the shops quite a bit, so most if not all of your suggestions will be added. Thanks.
