### ISSUE TITLE
Some minor problems and suggestions during use

### ISSUE THREAD

**Issue by lichenglin19901123** [ericgrandt/TotalEconomy#286]
Sponge Version:  2705
Forge Version:  3243
Total Economy Version: 1.8.1 

### Description of issue
This is a very comprehensive plugin, I like it very much, but I still have various problems during use.I hope that you can supplement the wiki page so that you can make better use of this great plugin.

1. It is recommended to put the permissions of various occupations on the following interface: https://ore.spongepowered.org/Erigitic/Total-Economy/pages/Permissions. Or in the process of setting up the work, it is stated that the server administrator needs to give the corresponding permission to the player in advance.

2. In addition, in the Jobset.conf configuration file, some items are obtained using "", and another part is not used. It is recommended to indicate the reason. In addition, if you want to add items to other modules, you need to use "" or other methods to obtain item data, you should also provide examples. For example, if there is another fish in the module or other items that can be obtained by using the fishing behavior, how should I add it in the configuration table? I tried it is invalid, whether or not I use "".

3. I want to set up a new career. I can get experience and gold coins by eating food or completing sleep. This will be very interesting, but this plugin does not currently support eating and sleeping data. I hope the next version can be stand by.
### Related Configuration Files
Create a Gist (https://gist.github.com/) for each configuration file related to this issue

**Comment by MarkL4YG** [comment]
I want to answer some of those points while getting back to the others later:

> 2.

The configuration format is HOCON which is provided by Sponge. They already have documentation on that. I personally think it would be redundand having to document this in the plugin wiki too.

> 3. 

Please provide a separate feature request for that so we can track stuff better :)  
  

I generally agree with you that the documentation is a little outdated and somewhat incomplete here and there. Maybe a proper documentation/wiki service would be a better place than github? Gitbooks maybe? I'm not sure whether or not that may improve contributions to the documentation.
