### ISSUE TITLE
Remove database table generation for disabled features

### ISSUE THREAD

**Issue by tridaak** [ericgrandt/TotalEconomy#287]
Sponge Version: SpongeForge-1.12.2-2705-7.1.0-BETA-3148
Forge Version: Forge 14.23.4.2705
Total Economy Version: TotalEconomy-1.8.1

### Description of issue
Have all job related stuff turned off in my configuration, but it still generated databases for them, and a bit surprisingly as well created the default jobs as well: https://i.imgur.com/sVxfo0R.png
Wondering if this could be removed to prevent clutter in databases.

### Related Configuration Files
https://gist.github.com/tridaak/e15148b2d4b1d55df82637e0b46b2136
https://gist.github.com/tridaak/fbe3e191b192444a036aaa33972f7dec
https://gist.github.com/tridaak/9432b5fc411ca3b544e6c75158d0a8d1

**Comment by MarkL4YG** [comment]
It is creating the tables not full databases though ':D 
Also proper db viewers will group tables using the same prefix so you clutter issue wouldn't appear.

I may also consider making the table creation optional IF it doesn't get to complicated in the sql-refactor.
