### ISSUE TITLE
Job Buffs

### ISSUE THREAD

**Issue by liampearson96** [ericgrandt/TotalEconomy#308]
Maybe some sort of system where a when a player ranks up, they get a buff at certain levels for example, when a miner reaches level 20 they get fortune 3 for 20 minutes, or efficiency for 20 minutes ect..

**Comment by MarkL4YG** [comment]
Sounds interesting.  
As for implementation some sort of more abstract bonus feature which can grant items, permissions, etc.  
I think one could work with this idea.

**Comment by liampearson96** [comment]
Yeah so, when the player reaches X level they actually get rewarded for reaching that level other than it just being a level for instance.

**Comment by TonyoBlaster** [comment]
rip

**Comment by TonyoBlaster** [comment]
RIP ?

**Comment by MarkL4YG** [comment]
@TonyoBlaster no?
