### ISSUE TITLE
UltimateChat name of the job in chat

### ISSUE THREAD

**Issue by LeChevalierDOr** [ericgrandt/TotalEconomy#328]
Simple question, is it possible to show the name of the job in the chat with UltimateChat?
If so, what is the tag {nameofthetag} to add in the UltimateChat configuration?
If not, would it be possible to add this feature?

Thank you in advance,
Sincerely.

**Comment by Erigitic** [comment]
I don't think it's possible at the moment. We can probably get this added in though.
