### ISSUE TITLE
Translation incomplete

### ISSUE THREAD

**Issue by ghost** [ericgrandt/TotalEconomy#332]
Request for being able to translate ALL the messages, like: 

[BEAK], [PLACE] and the rest when we do /job info

"Jobs available: ..." when we do /job

I think that's enough for the moment.

**Comment by TonyoBlaster** [comment]
"UP" ?

**Comment by MarkL4YG** [comment]
That means, I agree with your opinion and I would favor an implementation of this. 😉

**Comment by TonyoBlaster** [comment]
Yeah I know bro, I wrote "Up" for "Up" the issue, not for ur message... :')

By the way, is it possible to be able to translate the actions ? Like, for the /job info, replace the "minecraft:iron_ore" with "Iron Ore" ? U see ?

**Comment by MarkL4YG** [comment]
I think that would be possible. As a plugin, we should have access to the registry and therefore, should be able to get localized names for the entities/blocks 🤔 .  
However, I did not yet look into this.

**Comment by TonyoBlaster** [comment]
"UP" as always

**Comment by MarkL4YG** [comment]
There is absolutely no need to bump issues.  
We have not forgotten their existence. It's just that there needs to be spare time/capacity available to implement this.

**Comment by YoSuboDeToh** [comment]
UP
