### ISSUE TITLE
Shop notifications

### ISSUE THREAD

**Issue by BelowAverageBen** [ericgrandt/TotalEconomy#333]
### Just a little suggestion: 
It would be nice to have a toggleable notification every time someone buys from your chest shop. It could include the amount of money received, from whom you received it and your new balance. Just something people have been asking for on my little server. It might start some discourse about fairness in prices or just thanking someone. Thanks for your time.

**Comment by MarkL4YG** [comment]
Shouldn't be too hard :thinking:.
Add a message, add a new toggleable player option and send that message when an item is bought.
