### ISSUE TITLE
Chest Shops could use Q throw item

### ISSUE THREAD

**Issue by 879492767** [ericgrandt/TotalEconomy#346]
Sponge Version:  spongeforge-1.12.2-2768-7.1.6-RC3616
Forge Version:  forge-1.12.2-14.23.5.2768-universal
Total Economy Version:  TotalEconomy-1.8.1

**Comment by MarkL4YG** [comment]
Hey there 👋 ,
can you explain, what exactly you mean?

**Comment by 879492767** [comment]
yes, my player use chest shop to sell item, these item in chest shop could use q to throw out, don't need pay for item

**Comment by MarkL4YG** [comment]
The owner of a chest shop can already remove items from the shop :thinking:   
I don't think I understand what you are trying to suggest :confused:

**Comment by 879492767** [comment]
it's not suggest, it's a bug...  not owner, other player could throw item in chest shop

**Comment by MarkL4YG** [comment]
Interesting. I'll check on that during the next days 😅

**Comment by 879492767** [comment]
thank you!
