### ISSUE TITLE
Connection leak detection + Crash

### ISSUE THREAD

**Issue by DiamondArrow** [ericgrandt/TotalEconomy#349]
Sponge Version:  spongeforge-1.12.2-2768-7.1.6-RC3616
Forge Version:  forge-1.12.2-14.23.5.2809
Total Economy Version:  1.8.1

### Description + Error log
Server's been crashing daily with similar crash reports: https://pastebin.com/6CQtymNu
Before the crash, console would show this: https://pastebin.com/fsTnLJvV

### Steps to reproduce
Seems to be /baltop. Doesn't seem to happen everytime though.

**Comment by MarkL4YG** [comment]
Hi,
can you retry this with TotalEconomy 1.8.2 (which you will need to build yourself from the repository) and get back to us on whether or not that changes things?

**Comment by DiamondArrow** [comment]
Sorry I'm not familiar with the process and feel like a blind man walking a dog following online guides with jargon. Could you help me out or provide me with a jar?

**Comment by MarkL4YG** [comment]
No problem:
1. Clone the repository (there's this green "download ZIP" button on the top right"
2. Unpack the archive
3. From acommand line, run ``./gradlew.bat build`` or ``./gradlew build`` if you're on Linux.
4. After the build finished, you can find the plugin jar in the ``build/libs/`` directory.

**Comment by liampearson96** [comment]
Hello guys,

I just tried the 1.8.2 version and i still get the same lag.

I believe it is because there are X amount of accounts and it takes a while to calculate them.

**Comment by MarkL4YG** [comment]
1.8.2 should include a change that limits the DB query result to 10 results which should not take very long.

**Comment by liampearson96** [comment]
It’s about 2 seconds however it’ll still cause a noticeable pause on the server.

**Comment by MarkL4YG** [comment]
hmm.. 🤔 can you provide some rough details about your database? Which server you use, how many users & accounts you have as well as information on what machine your servers are running on?  
This would help me think of how this delay is caused and how to tackle it.

**Comment by xion87** [comment]
can i have the 1.8.2 jar?

**Comment by MarkL4YG** [comment]
You could just repeat the steps from [my comment above](https://github.com/Erigitic/TotalEconomy/issues/349#issuecomment-506950734) and you'll have the fresh jar file. 😅   
If you have any questions, feel always free to ask 🙂

**Comment by LemADEC** [comment]
Lag is reproduced without a DB.
I did a profiling over 5 mn spamming the `/baltop` command.
From a quick check, the lag is coming from AccountManager.addNewCurrenciesToAccount doing a save on each account as it's read from disk.
It appears the underlying library doesn't cache and it'll rebuild everything on each save which consumes lots of RAM and CPU time.
There's also issues with hashtags computation which are causing a lot of CPU time with good signs of that "Shlemiel the painter’s algorithm" in effect (i.e. it doesn't scale well).

Long story short, I suggest to only save when there's actually a change detected here https://github.com/ericgrandt/TotalEconomy/blob/1fd1348091db8d14d1f7aa2f12f8cfd4ab2763e8/src/main/java/com/erigitic/config/AccountManager.java#L450 and here https://github.com/ericgrandt/TotalEconomy/blob/1fd1348091db8d14d1f7aa2f12f8cfd4ab2763e8/src/main/java/com/erigitic/config/AccountManager.java#L471 .

Here's a screenshot from that profiling:
![image](https://user-images.githubusercontent.com/4776032/120723392-ee4a7c80-c4d1-11eb-8e4a-925200e8b3e2.png)

**Comment by Nbgreen** [comment]
any updates on this issue im having the same problems

**Comment by ericgrandt** [comment]
Hey @Nbgreen, this plugin is being completely rewritten for the latest versions of Minecraft and Sponge, so this should no longer be an issue once that releases. As well as that, I don't plan to bring the baltop command back in this rewritten version.

**Comment by Nbgreen** [comment]
Ah what is the most up to date version for 1.12.2 MC. 
Also that’s sad to here.
 /baltop gives players a good reason to use the economy. they like to know who has the most money and try to beat those people

**Comment by ericgrandt** [comment]
@Nbgreen this is the most recent version, though it is 4 years old: https://ore.spongepowered.org/Erigitic/Total-Economy/versions/1.8.1. The baltop command may make a come back, just no plans at this point.
