### ISSUE TITLE
Problem with Safetrade.

### ISSUE THREAD

**Issue by AceGamer45** [ericgrandt/TotalEconomy#357]
Sponge Version:  Sponge 2768-7.1.6-RC3616
Forge Version:  14.23.5.2838
Total Economy Version:  1.8.1

### Description of issue
When I start a safetrade, there is a problem with TotalEconomy that I didn't have when I was using another economy plugin.

I don't know if the error is from Safetrade or TotalEconomy.

### Console errors
https://pastebin.com/ULBRWdcF

### Related Configuration Files
Create a Gist (https://gist.github.com/) for each configuration file related to this issue

**Comment by MarkL4YG** [comment]
Hi,  
I am not quite sure what SafeTrade is but it appears that may not even matter.  
Can you please attach your full log file as it appears you're running into a malformed SQL statement for some reason.
I would also like to see a structure view of the database tables for TotalEconomy on your database server so I can see whether or not the schema is correctly applied. 🤔

**Comment by AceGamer45** [comment]
In itself the only problem is when the player wants to add money to the safetrade, it takes the money away but safetrade tells him that he doesn't have enough money and it doesn't put him in the safetrade so the money just disappears.

I didn't have this problem with the other economy plugin so that's why I don't know if the problem comes from safetrade or totaleconomy.

Structure database :  https://i.gyazo.com/2945cdbd4d015c11deea8eef494bf21c.png

For fulls logs, I don't think it's necessary, there's no error message or totaleconomy or safetrade message that specifies that it has detected an economy plugin and I confirm because it puts the currency correctly, the problem is simply what I described above.
