### ISSUE TITLE
Job does not exist (bug)

### ISSUE THREAD

**Issue by RexusOhm** [ericgrandt/TotalEconomy#361]
Sponge Version:  1.12.2-2838-7.1.9
Forge Version:  14.23.5.2847
Total Economy Version:  1.8.1

### Description of issue
Jobs are added to the configuration file, but writes that they do not exist.

`Reeve {
        require {
            job="miner"
            level=20
            permission="totaleconomy.job.miner"
        }
        salary=150
        sets=[
            ores
        ]
    }
	Senior_warrior {
        require {
            job="warrior"
            level=20
            permission="totaleconomy.job.warrior"
        }
        salary=150
        sets=[
            mobs
        ]
    }
	Experienced_miner {
        require {
            job="Reeve"
            level=30
            permission="totaleconomy.job.miner"
        }
        salary=250
        sets=[
            ores
        ]
    }
	Experienced_warrior {
        require {
            job="Senior_warrior"
            level=30
            permission="totaleconomy.job.warrior"
        }
        salary=250
        sets=[
            mobs
        ]
    }
	Legendary_miner {
        require {
            job="Experienced_miner"
            level=50
            permission="totaleconomy.job.miner"
        }
        salary=550
        sets=[
            ores
        ]
    }
	Legendary_warrior {
        require {
            job="Experienced_warrior"
            level=50
            permission="totaleconomy.job.warrior"
        }
        salary=550
        sets=[
            mobs
        ]
    }`
### Console errors
![Аннотация 2020-02-07 145140](https://user-images.githubusercontent.com/59621106/74027537-688bef00-49b9-11ea-9396-a88b273cd829.jpg)

![А](https://user-images.githubusercontent.com/59621106/74027855-113a4e80-49ba-11ea-812a-6566487d2424.jpg)

> How to fix this bug?

### Related Configuration Files
https://gist.github.com/newresource-dev/e0a4b4c71aec86e95175229cb4830ce6

**Comment by MarkL4YG** [comment]
Hello there :wave: 
Can you please attach your server logs so we can see whether or not something is preventing the job configuration from being loaded?

**Comment by newresource-dev** [comment]
**last logs:**
[latest.log](https://github.com/Erigitic/TotalEconomy/files/4220859/latest.log)
[debug.log](https://github.com/Erigitic/TotalEconomy/files/4220862/debug.log)

**Comment by MarkL4YG** [comment]
Just mentioning that I did not forget about this. At the moment, I just have very few spare time.  
It seems like there is no syntactical configuration issue on your side. However, please check whether or not writing the jobs names in all lowercase fixes the issue.
