### ISSUE TITLE
How to make a scoreboard with total economy

### ISSUE THREAD

**Issue by modedway** [ericgrandt/TotalEconomy#365]
Sponge Version:  7.1.7
Forge Version:  1.12.2
Total Economy Version latest ????
### Related Configuration Files
Create a Gist (https://gist.github.com/) for each configuration file related to this issue

**Comment by macks2008** [comment]
is this supposed to be a feature request? Even if the feature is supposed to exist already (I just got started using the plug-in myself so I wouldn't know), will you should probably add more details than just the current issue title. What are you trying to and what have you tried? Where are you stuck at?
