### ISSUE TITLE
Admin powers limited

### ISSUE THREAD

**Issue by omerbadawy11** [ericgrandt/TotalEconomy#366]
Hello, 
Firstly, I'd like to say thank you for the amazing Plugin!
It's just I'm encountering a small problem, how can I (an Admin) break or cancel shops that players made? is there a clean way to handle shops that others made that I no longer need to keep?
also, is there a way to make chest shops on my server without a player collecting money? like the server collects the money and it just gets voided.

**Comment by Erigitic** [comment]
Currently not possible to remove someone else's shop. This was overlooked by me during development of the chest shops. Total Economy is currently in the process of being rewritten from the ground up, so I'll be sure to fix this issue. As well as that, "server shops" are planned to be added to the rewrite as well.

**Comment by omerbadawy11** [comment]
Alright, I see. Well please do let me know when you happen to finish it. I totally support you!

Small feature if you happen to be interested in adding it, chest shops are great but having NPCs based on the mobs of the server is even better and it feels more immersive!! I checked out and the only plugin that does it is villagershops except they do it very badly in my opinion. that plugin failed me with every single modpack which defeats the purpose of spongeforge. I just thought id mention that feature, it would be amazing!

**Comment by Erigitic** [comment]
Great suggestion! Once Sponge 1.14 is release, NPC shops are planned to be the first type of shop I add.

**Comment by omerbadawy11** [comment]
Unfortunately that 1.14 forge is still unstable. I would've loved to have your plugin in 1.12 but best of luck!
have a great day

**Comment by pinkpig3777** [comment]
Just to clarify, which versions of Forge does this plugin support? I just realized I don't see it mentioned anywhere.

I'm using a 1.12.2 server.

**Comment by omerbadawy11** [comment]
> Just to clarify, which versions of Forge does this plugin support? I just realized I don't see it mentioned anywhere.
> 
> I'm using a 1.12.2 server and may like to use this plugin if 1.12.2 is supported.
> 
> Edit: Just realized I guess the plugin is abandoned? As it hasn't been updated in two years.

I'm using it on my 1.12.2 sponeforge server and I think it's amazing, shops lack a lot though sadly. I'm still looking for a good shops plugin to use along this

**Comment by Erigitic** [comment]
@pinkpig3777 The plugin is not abandoned, just waiting on a 1.14 release for Sponge as it will allow for better handling of blocks and items as they all have their own unique name. No more having to deal with variants. This will lead to a much better implementation of both jobs and shops. The plugin has begun the process of being completely rewritten: https://github.com/Erigitic/TotalEconomy/tree/terewritten.
