### ISSUE TITLE
Asynchronous File Saving

### ISSUE THREAD

**Issue by notphage** [ericgrandt/TotalEconomy#369]
Sponge Version:  7.2.0
Forge Version:  1.12.2-14.23.5.2854
Total Economy Version:  1.8.2

### Description of issue
File saving happens on the main thread in most cases. We've forked the plugin to use sponge's executor service that you use in autosave on all saving functionality, however this may be a change you're interested in implementing yourself.

### Console errors
None

### Steps to reproduce
Cause any file to be saved. A larger than normal file will cause the main thread to hang.

### Related Configuration Files
Create a Gist (https://gist.github.com/) for each configuration file related to this issue

**Comment by MarkL4YG** [comment]
Hi there :)
If you already have the code, why not clean it up a bit and submit a PR for that feature 🙂 
We would love to see it ❤️
