### ISSUE TITLE
Total economy, Shop command doesnt work

### ISSUE THREAD

**Issue by Zarosi** [ericgrandt/TotalEconomy#375]
Good Day, How to use admin shop?
Also my /shop command doesnt work. How to fix this? Is there any other way to fix this?

**Comment by sora7672** [comment]
> Also my /shop command doesnt work. How to fix this? Is there any other way to fix this?

Have you a permission plugin installed? Setup the permissions correctly? Also its allways good to include your Sponge&TE version for support. (Just searching for a similiar probelmthats why i replied :P )
