### ISSUE TITLE
Using adminpay to deduct currency from a player's balance can still result in a negative balance

### ISSUE THREAD

**Issue by Vulant** [ericgrandt/TotalEconomy#376]
Sponge Version:  1.12.2-2838-7.2.3
Forge Version:  14.23.5.2847
Total Economy Version:  1.8.1

### Description of issue
Using /adminpay <playername> -#currency can result in a negative balance
### Console errors
N/A
### Steps to reproduce
Example:
1. Have a 0 balance or anything under 100
2. Use /adminpay <playername> -100
3. Results in negative balance
### Related Configuration Files
Create a Gist (https://gist.github.com/) for each configuration file related to this issue
N/A

**Reason this is an issue for me:**
I am trying to allow players to convert from one currency to another by having the console or command block check to see if the deduction of currency#1 is successful. If it is successful, then it will add currency#2. This is not possible if every time I use /adminpay to deduct currency, it will work since it results in a negative balance.

I have gone through the past issues on github and see that this idea has come up, but wasn't sure if it was abandoned or not. 
If it is abandoned, please let me know. Thank you!

**Comment by MarkL4YG** [comment]
I would argue that this being an admin command should allow you to drop a players balance into the negatives. 🤔 
Technically this resembles debt to the server.
Maybe a flag of some sort could make this command cap at 0 in the future.

**Comment by Gablers** [comment]
My issue is pretty much identical to OP. 
I need a command to remove money, to give an item to the player. 
With negative numbers, they can spam it to no end.
Could you recommend a work around?

**Comment by zediious** [comment]
> My issue is pretty much identical to OP. 
> 
> I need a command to remove money, to give an item to the player. 
> 
> With negative numbers, they can spam it to no end.
> 
> Could you recommend a work around?

You could try using CarrotShop CMD shops in combination with total economy. Look at their wiki for instructions on cmd signs. You can hit a made shop sign with a stick to change the currency it will use.
