### ISSUE TITLE
issue with /job reload

### ISSUE THREAD

**Issue by Chaosx911** [ericgrandt/TotalEconomy#379]
Sponge Version:  
Forge Version:  
Total Economy Version:  1.8.1

### Description of issue
i was trying to reload my job config to add all thermal expansion ores and draconic evolutionores but i was getting an error saying it failed to reload
### Console errors
https://i.imgur.com/B6KxBVQ.png
### Steps to reproduce
/job reload
### Related Configuration Files
Create a Gist (https://gist.github.com/) for each configuration file related to this issue

**Comment by MarkL4YG** [comment]
Details regarding that error should be shown in the server console. Please provide your server logs so others can try to help you. 🙂
