### ISSUE TITLE
The farmer's job doesn't work.

### ISSUE THREAD

**Issue by MikaCookies** [ericgrandt/TotalEconomy#381]
Sponge Version:  spongeforge-1.12.2-2838-7.3.0.jar
Forge Version:  spongeforge-1.12.2-2838-7.3.0.jar
Total Economy Version:  Latest

When a player collects, for example, carrots or potatoes that were planted in the base world, he does receive the money. But if that player or another player plants carrots and legs and picks them up later, they get nothing.

**Comment by Erigitic** [comment]
Are you getting any error messages in the console?

**Comment by MikaCookies** [comment]
No. I'm going to try to explain myself as best I can.
When someone mines an ore he receives the money and the experience, but if he chops that ore with silk touch and then places it in the world and tries to mine it again, he receives nothing. That's fine.

But if someone breaks carrots, potatoes, etc., which were not based in the world, he does not receive anything. And that should not be so, because then the farmer's work is useless.

**Comment by Shiro-2306** [comment]
Bonjour j'ai aussi le même problème avec ce job de fermier malheureusement. Je n'ai aucun message d'erreur de la console.
Il se pourrait que cela vienne de notre version de forge ou de sponge car nous utilisons les mêmes versions...
