### ISSUE TITLE
Job level requirement

### ISSUE THREAD

**Issue by kriticalvinho** [ericgrandt/TotalEconomy#397]
Sponge Version:  spongeforge-1.12.2-2838-7.3.0.jar
Forge Version:  forge-1.12.2-14.23.5.2855-installer.jar
Total Economy Version:  TotalEconomy-1.8.1.jar

### Description of issue

I have the same issue with job level requirement #274 

How can i fix it?

**Comment by ericgrandt** [comment]
What's the error that you're receiving?

**Comment by kriticalvinho** [comment]
When I create a job and it has a level requirement, everyone can use the job sign. 

The level requirement does not work

**Comment by MsVixxy** [comment]
Exact same issue here, no error the signs just don't check for the job requirements at all for anybody.

Maybe I'm missing something obvious though so dropping the jobs.conf here.
[jobs.conf.txt](https://github.com/ericgrandt/TotalEconomy/files/7251669/jobs.conf.txt)
l.
