### ISSUE TITLE
Economy withdraw and deposit do not follow behaviour of Vault JavaDoc

### ISSUE THREAD

**Issue by Sytm** [ericgrandt/TotalEconomy#414]
According to the Vault JavaDocs it seems to be fine to withdraw (and deposit) an amount of zero, but this plugin rejects that transaction [here](https://github.com/ericgrandt/TotalEconomy/blob/66dcae8b230dcb3d633883bba9b91505d51a6af1/totaleconomy-common/src/main/java/com/ericgrandt/totaleconomy/common/econ/CommonEconomy.java#L72-L77)

Vault JavaDocs:
![grafik](https://github.com/ericgrandt/TotalEconomy/assets/21055143/54a33906-6043-4eaf-ad4a-4800a131e6e0)

An example for zero to be a valid amount would be if the account of a player is frozen, so the transaction could still be denied, even if the player has sufficient funds.

**Comment by Sytm** [comment]
For some context: My plugin allows admins providing a custom formula, so they can customize the price increase for teleportations (like constant price, linear growth, exponential growth, etc). My plugin uses the Vault API to query and modify the amount of money a player has.

One user reported an issue that they cannot teleport when using a formula that evaluates to zero for the first teleport and then increases with each successive one, when using this economy plugin.

My issue here is just based on the technically correct behavior according the Vault API that it's implementations should follow (I would at least expect them to do), because some economy plugins might support freezing and have different behavior, while this one doesn't but shouldn't disallow zero withdrawals.

**Comment by ericgrandt** [comment]
Thanks for the context @Sytm. This makes sense. I have an idea that'll allow for the Total Economy implementation of Vault to allow zero as a value while also preventing it from other areas in the plugin where zero shouldn't be allowed (e.g. Total Economy's `pay` command). Best of both worlds I think. I'll let you know when that's in place. Thanks again!

**Comment by ericgrandt** [comment]
Hi @Sytm, give this new release a shot: https://modrinth.com/plugin/total-economy/version/0.12.1. Thanks

**Comment by ericgrandt** [comment]
Hi @Sytm, following up again to see if this is resolved. If there's no response in the next couple of days I'll close this issue to avoid it getting too stale, though feel free to reopen if it is still an issue. Thanks.

**Comment by Sytm** [comment]
Sorry for not answering, but spinning up a MySQL server for testing is always a bit annoying.
I have tested the edge case and it works now without any problems.

I also noticed that the released version string and the version in your plugin.yml do not match
