### ISSUE TITLE
Error when using per-world Vault Economy methods

### ISSUE THREAD

**Issue by Phoenix616** [ericgrandt/TotalEconomy#426]
Currently there is a NotImplementedException thrown when trying to use the per-world Vault Economy methods, this does not match VaultAPI specs (which [says](https://github.com/MilkBowl/VaultAPI/blob/8bad2c479f531436b4b0694f5696b501d0afef3e/src/main/java/net/milkbowl/vault/economy/Economy.java#L137) to use the global balance instead) and therefore breaks any plugin which uses those methods to provide per-world economy support in case the economy plugin supports it. (e.g. https://github.com/ChestShop-authors/ChestShop-3/issues/605)

**Comment by ericgrandt** [comment]
Fixed in 0.13.2, thanks for the report @Phoenix616.
