### ISSUE TITLE
Feature request Jobs for specific worlds

### ISSUE THREAD

**Issue by mister-man** [ericgrandt/TotalEconomy#90]
Hallo together, 

it would be nice,  if it is possible to activate jobs for specific world's. In my case my server has a survival and a creative game mode,  but the players can earn money  by placing dia ore and remove it in the creative world. 

Thanks

**Comment by Erigitic** [comment]
I will look into this and I am pretty sure it is possible.

**Comment by MarkL4YG** [comment]
> but the players can earn money by placing dia ore and remove it in the creative world

That shouldn't be the case anymore

**Comment by Erigitic** [comment]
Is there a use case for this anymore considering blocks placed by players no longer give out rewards? @MarkL4YG @mister-man

**Comment by MarkL4YG** [comment]
@Erigitic hmm... 🤔 I guess there may be a reason for disabling jobs in some worlds due to blocks placed by plugins not counting as placed by players. I could imagine a WorldEdit world where this could happen for example.  
Maybe we should take a closer look at this before final decision.
